[package]
name = "ast"
version = "0.1.0"
edition = "2021"

[dependencies]
# cargo managed dependencies
codespan = "0.11.1"
codespan-reporting = "0.11.1"
logos = "0.14.0"

# project dependencies
common = { path = "../common" }